channels:
  - conda-forge
  - nodefaults
dependencies:
  # runtimes
  - python >=3.8,<3.9.0a0
  - nodejs >=14,<15.0.0a0
  # setup deps
  - doit
  - pip
  - twine
  - jupyter-packaging
  - wheel
  - packaging
  - setuptools
  # lab deps
  - tornado >=6.1
  - jinja2 >=2.10
  - nbclassic >=0.2,<1
  - ipython
  # server deps
  - pytz
  - babel
  - json5
  - jsonschema >=3.0.1
  - jupyter_server >=1.4,<2
  # test
  - openapi-core >=0.13.8,<0.14
  - pytest
  - pytest-check-links
  - pytest-console-scripts
  - pytest-cov
  - pytest-tornasync
  - requests-cache
  - ruamel.yaml
  # TODO: pr for p-c-s
  - pytest-runner
  - strict-rfc3339
  - codecov
  - ipykernel
  # docs
  - recommonmark
  - sphinx
  - sphinx_rtd_theme
  - sphinx-copybutton
  # linting
  - black
  - flake8
